name: ceksantap
description: "Cek Rasa Anda"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


  image_cropper: ^9.1.0

  lottie: ^3.3.0
  cupertino_icons: ^1.0.8

  provider: ^6.1.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  camera: ^0.10.6


  http: ^1.2.2
  image: ^4.5.2
  intl: ^0.20.2
  tflite_flutter: ^0.11.0
  firebase_core: ^3.12.0
  firebase_ml_model_downloader: ^0.3.3+1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/ceksantap_logo.png"

flutter:


  uses-material-design: true

  assets:
    - .env
    - assets/labels.txt
    - assets/animation/
    - assets/image/
    - assets/lottie/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic

    - family: SansitaSwashed
      fonts:
        - asset: assets/fonts/SansitaSwashed-Regular.ttf
        - asset: assets/fonts/SansitaSwashed-Light.ttf
          weight: 300
        - asset: assets/fonts/SansitaSwashed-Medium.ttf
          weight: 500
        - asset: assets/fonts/SansitaSwashed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SansitaSwashed-Bold.ttf
          weight: 700
        - asset: assets/fonts/SansitaSwashed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SansitaSwashed-Black.ttf
          weight: 900
